version: '3.9'

services:
  analysis:
    hostname: mock-analysis
    container_name: cynthus-mock-analysis
    restart: unless-stopped
    image: cynthus/mock-analysis:latest
    build:
      context: ./containers/analysis
    environment:
      - 'TZ=${TIME_ZONE}'
      - 'PYTHONPATH=/opt/app/shared/src:/opt/app/src'
      - 'PYTHONUNBUFFERED=1'
    volumes:
      - './containers/analysis/bin:/opt/app/bin'
      - './containers/analysis/src:/opt/app/src'
      - './containers/analysis/test:/opt/app/test'
    expose:
      - '${API_PORT}/tcp'
    networks:
      - net
      - vnet
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:${API_PORT}/" ]
      start_period: 30s
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file

  auth:
    hostname: mock-auth
    container_name: cynthus-mock-auth
    restart: unless-stopped
    image: cynthus/mock-auth:latest
    build:
      context: ./containers/auth
    environment:
      - 'TZ=${TIME_ZONE}'
      - 'PYTHONPATH=/opt/app/shared/src:/opt/app/src'
      - 'PYTHONUNBUFFERED=1'
    volumes:
      - './containers/auth/bin:/opt/app/bin'
      - './containers/auth/src:/opt/app/src'
      - './containers/auth/test:/opt/app/test'
    expose:
      - '${API_PORT}/tcp'
    networks:
      - net
      - vnet
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:${API_PORT}/" ]
      start_period: 30s
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file

  chat:
    hostname: mock-chat
    container_name: cynthus-mock-chat
    restart: unless-stopped
    image: cynthus/mock-chat:latest
    build:
      context: ./containers/chat
    environment:
      - 'TZ=${TIME_ZONE}'
      - 'PYTHONPATH=/opt/app/shared/src:/opt/app/src'
      - 'PYTHONUNBUFFERED=1'
    volumes:
      - './containers/chat/bin:/opt/app/bin'
      - './containers/chat/src:/opt/app/src'
      - './containers/chat/test:/opt/app/test'
    expose:
      - '${WEB_PORT}/tcp'
    networks:
      - net
      - vnet
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:${WEB_PORT}/" ]
      start_period: 30s
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file

  portal-api:
    hostname: mock-portal-api
    container_name: cynthus-mock-portal-api
    restart: unless-stopped
    image: cynthus/mock-portal-api:latest
    build:
      context: ./containers/portal-api
    environment:
      - 'TZ=${TIME_ZONE}'
      - 'PYTHONPATH=/opt/app/shared/src:/opt/app/src'
      - 'PYTHONUNBUFFERED=1'
    volumes:
      - './containers/portal-api/bin:/opt/app/bin'
      - './containers/portal-api/src:/opt/app/src'
      - './containers/portal-api/test:/opt/app/test'
    expose:
      - '${API_PORT}/tcp'
    networks:
      - net
      - vnet
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:${API_PORT}/" ]
      start_period: 30s
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file

  portal-web:
    hostname: mock-portal-web
    container_name: cynthus-mock-portal-web
    restart: unless-stopped
    image: cynthus/mock-portal-web:latest
    build:
      context: ./containers/portal-web
    environment:
      - 'TZ=${TIME_ZONE}'
      - 'PYTHONPATH=/opt/app/shared/src:/opt/app/src'
      - 'PYTHONUNBUFFERED=1'
    volumes:
      - './containers/portal-web/bin:/opt/app/bin'
      - './containers/portal-web/src:/opt/app/src'
      - './containers/portal-web/test:/opt/app/test'
    expose:
      - '${WEB_PORT}/tcp'
    networks:
      - net
      - vnet
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:${WEB_PORT}/" ]
      start_period: 30s
      interval: 20s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file

networks:
  net:
    external: true
    name: cynthus_net
  vnet:
    internal: true
    name: cynthus_mock_vnet
    ipam:
      config:
        - subnet: ${CYNTHUS_MOCK_VNET_SUBNET}
