version: '3.9'

services:
  analysis:
    hostname: analysis-mock
    container_name: cynthus-analysis-mock
    restart: unless-stopped
    image: cynthus/analysis-mock:latest
    build:
      context: ./containers/analysis
    environment:
      - TZ=${TIME_ZONE}
      - PYTHONPATH=/opt/app/shared/src:/opt/app/src
    volumes:
      - './configs:/opt/app/configs'
      - './containers/analysis/bin:/opt/app/bin'
      - './containers/analysis/src:/opt/app/src'
      - './containers/analysis/test:/opt/app/test'
    expose:
      - ${API_PORT}/tcp
    networks:
      - net
      - vnet
    logging:
      driver: json-file

  auth:
    hostname: auth-mock
    container_name: cynthus-auth-mock
    restart: unless-stopped
    image: cynthus/auth-mock:latest
    build:
      context: ./containers/auth
    environment:
      - TZ=${TIME_ZONE}
      - PYTHONPATH=/opt/app/shared/src:/opt/app/src
    volumes:
      - './configs:/opt/app/configs'
      - './containers/auth/bin:/opt/app/bin'
      - './containers/auth/src:/opt/app/src'
      - './containers/analysis/test:/opt/app/test'
    expose:
      - ${API_PORT}/tcp
    networks:
      - net
      - vnet
    logging:
      driver: json-file

  chat:
    hostname: chat-mock
    container_name: cynthus-chat-mock
    restart: unless-stopped
    image: cynthus/chat-mock:latest
    build:
      context: ./containers/chat
    environment:
      - TZ=${TIME_ZONE}
      - PYTHONPATH=/opt/app/shared/src:/opt/app/src
    volumes:
      - './configs:/opt/app/configs'
      - './containers/chat/bin:/opt/app/bin'
      - './containers/chat/src:/opt/app/src'
      - './containers/chat/test:/opt/app/test'
    expose:
      - ${WEB_PORT}/tcp
    networks:
      - net
      - vnet
    logging:
      driver: json-file

  portal:
    hostname: portal-mock
    container_name: cynthus-portal-mock
    restart: unless-stopped
    image: cynthus/portal-mock:latest
    build:
      context: ./containers/portal
    environment:
      - TZ=${TIME_ZONE}
      - PYTHONPATH=/opt/app/shared/src:/opt/app/src
    volumes:
      - './configs:/opt/app/configs'
      - './containers/portal/bin:/opt/app/bin'
      - './containers/portal/src:/opt/app/src'
      - './containers/portal/test:/opt/app/test'
    expose:
      - ${WEB_PORT}/tcp
    networks:
      - net
      - vnet
    logging:
      driver: json-file

networks:
  net:
    external: true
    name: cynthus_net
  vnet:
    internal: true
    name: cynthus_vnet_mocks
    ipam:
      config:
        - subnet: ${CYNTHUS_MOCK_VNET_SUBNET}
